name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
          cache-version: 3  # 更新缓存版本

      - name: Install Dependencies
        run: |
          sudo apt-get install -y zlib1g-dev
          bundle config path vendor/bundle
          bundle install --jobs 4

      - name: Clean and Build
        run: |
          bundle exec jekyll clean
          bundle exec jekyll build --trace

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main
          force_orphan: true
